### ISSUE TITLE
Wrong Import Statement That results in crashing.

### ISSUE THREAD

**Issue by Mrhb787** [Surya1231/ContestMania#10]
In `./src/store/reducers/ProblemsReducer.js`

#### Current
``` 
import { problemsCategories } from '../../api/data/problemsData';
```

### Error
![Screenshot 2022-02-03 195900](https://user-images.githubusercontent.com/56078689/152362535-45f65ea8-d5c3-4673-811f-765a18e5aca7.png)

### Correct Import
```
import { problemsCategories } from '../../api/data/ProblemsData';
```

- Would Like to work on It and Contribute More.

**Comment by Surya1231** [comment]
Can you create pull request to address this problems?

**Comment by Mrhb787** [comment]
@Surya1231 I have send the PR

**Comment by Surya1231** [comment]
I will take a look at it today and will merge and deploy
