### ISSUE TITLE
no updation of upcoming contest

### ISSUE THREAD

**Issue by 123vin123** [Surya1231/ContestMania#7]
plz look at your system there is no update of upcoming contest

**Comment by Surya1231** [comment]
can you please attach some screenshot of your problem

**Comment by 123vin123** [comment]
when i click on upcoming it shows something went wrong .

**Comment by pranchalshringi** [comment]
![image](https://user-images.githubusercontent.com/63733817/112794409-7781a500-9084-11eb-9a63-5f774417352d.png)
